export const CREATE = 'CREATE'
export const LOGIN = 'LOGIN'
export const UPDATE = 'UPDATE'
export const CHECK = 'CHECK'
export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
