import {addIcons} from 'ionicons'
import {
  add,
  alert,
  arrowBack,
  arrowDropleft,
  at,
  calendar,
  camera,
  checkmark,
  close,
  contact,
  create,
  flag,
  funnel,
  images,
  informationCircle,
  list,
  locate,
  lock,
  logoFacebook,
  logoInstagram,
  mail,
  map,
  more,
  person,
  pin,
  search,
  settings,
  share,
  speedometer,
  stats,
  trash,
  globe
} from 'ionicons/icons'

addIcons({
  'ios-add': add.ios,
  'md-add': add.md,
  'ios-arrow-back': arrowBack.ios,
  'md-arrow-back': arrowBack.md,
  'ios-alert': alert.ios,
  'md-alert': alert.md,
  'ios-at': at.md,
  'md-at': at.md,
  'ios-calendar': calendar.ios,
  'md-calendar': calendar.md,
  'ios-camera': camera.ios,
  'md-camera': camera.md,
  'ios-checkmark': checkmark.md,
  'md-checkmark': checkmark.md,
  'ios-close': close.md,
  'md-close': close.md,
  'ios-contact': contact.md,
  'md-contact': contact.md,
  'ios-create': create.md,
  'md-create': create.md,
  'ios-person': person.md,
  'md-person': person.md,
  'ios-images': images.ios,
  'md-images': images.md,
  'ios-list': list.ios,
  'md-list': list.ios,
  'ios-locate': locate.md,
  'md-locate': locate.md,
  'ios-location': pin.ios,
  'md-location': pin.md,
  'ios-map': map.md,
  'md-map': map.md,
  'ios-filter': funnel.md,
  'md-filter': funnel.md,
  'ios-flag': flag.ios,
  'md-flag': flag.md,
  'ios-globe': globe.md,
  'md-globe': globe.md,
  'ios-lock': lock.md,
  'md-lock': lock.md,
  'md-info': informationCircle.md,
  'ios-info': informationCircle.ios,
  'md-instagram': logoInstagram,
  'ios-instagram': logoInstagram,
  'md-facebook': logoFacebook,
  'ios-facebook': logoFacebook,
  'ios-stats': stats.ios,
  'md-stats': stats.ios,
  'ios-search': search.ios,
  'md-search': search.ios,
  'ios-settings': settings.md,
  'md-settings': settings.md,
  'ios-share': share.ios,
  'md-share': share.md,
  'ios-mail': mail.ios,
  'md-mail': mail.ios,
  'ios-more': more.ios,
  'md-more': more.md,
  'ios-trash': trash.ios,
  'md-trash': trash.ios,
  'ios-arrow-left': arrowDropleft.ios,
  'md-arrow-left': arrowDropleft.ios,
  'ios-speedometer': speedometer.ios,
  'md-speedometer': speedometer.md
})
