import {addIcons} from 'ionicons'
import {
  add,
  alert,
  arrowDropleft,
  at,
  calendar,
  camera,
  checkmark,
  funnel,
  images,
  informationCircle,
  lock,
  logoFacebook,
  logoInstagram,
  mail,
  map,
  person,
  pin,
  search,
  settings,
  speedometer,
  stats,
  trash
} from 'ionicons/icons'

addIcons({
  'ios-add': add.ios,
  'md-add': add.md,
  'ios-alert': alert.ios,
  'md-alert': alert.md,
  'ios-at': at.md,
  'md-at': at.md,
  'ios-calendar': calendar.ios,
  'md-calendar': calendar.md,
  'ios-camera': camera.ios,
  'md-camera': camera.md,
  'ios-checkmark': checkmark.md,
  'md-checkmark': checkmark.md,
  'ios-person': person.md,
  'md-person': person.md,
  'ios-images': images.ios,
  'md-images': images.md,
  'ios-location': pin.ios,
  'md-location': pin.md,
  'ios-map': map.md,
  'md-map': map.md,
  'ios-filter': funnel.md,
  'md-filter': funnel.md,
  'ios-lock': lock.md,
  'md-lock': lock.md,
  'md-info': informationCircle.md,
  'ios-info': informationCircle.ios,
  'md-instagram': logoInstagram,
  'ios-instagram': logoInstagram,
  'md-facebook': logoFacebook,
  'ios-facebook': logoFacebook,
  'ios-stats': stats.ios,
  'md-stats': stats.ios,
  'ios-search': search.ios,
  'md-search': search.ios,
  'ios-settings': settings.md,
  'md-settings': settings.md,
  'ios-mail': mail.ios,
  'md-mail': mail.ios,
  'ios-trash': trash.ios,
  'md-trash': trash.ios,
  'ios-arrow-left': arrowDropleft.ios,
  'md-arrow-left': arrowDropleft.ios,
  'ios-speedometer': speedometer.ios,
  'md-speedometer': speedometer.md
})
